resources:
  - url: http://127.0.0.1:5000/settings-card.js
    type: module
views:
  - cards:
      - type: custom:settings-card
        name: Settings Card Development
        entity: sun.sun
        test_gui: true
